X = input()
V = X.upper()
V = V.replace('B', 'v')
V = V.replace('E', 'ye')
V = V.replace('H', 'n')
V = V.replace('P', 'r')
V = V.replace('C', 's')
V = V.replace('Y', 'u')
V = V.replace('X', 'h')
print(V.lower())
